title: Steven Dao
email: ""
description: >
  A coder, Liverpool supporter, Naruto fan, Dog & Cat lover.
copyright: > # this means to ignore newlines until "baseurl:"
  © Steven Dao 2017
baseurl: "" # the subpath of the site
url: "" # the base hostname & protocol for the site
twitter_username: iamstevendao
github_username:  iamstevendao
portfolio: portfolio

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji

header_pages:
# - projects.md
- diary.md
- about.md
